describe("is.localdomain", function()
	local t, is, domain
	setup(function()
    t = require "t"
    is = t.is
    domain = t.net.domain
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(domain))
    assert.truthy(is.callable(is.localdomain))
  end)
  it("positive", function()
    assert.is_true(is.localdomain('my.local'))
    assert.is_true(is.localdomain(domain('my.local')))
  end)
  it("negative", function()
    assert.is_nil(is.localdomain('site.com'))
    assert.is_nil(is.localdomain(domain('site.com')))

    assert.is_nil(is.localdomain('8.8.8.8'))
    assert.is_nil(is.localdomain('com'))
    assert.is_nil(is.localdomain('.com'))
    assert.is_nil(is.localdomain('com.ru'))
    assert.is_nil(is.localdomain('.com.ru'))
    assert.is_nil(is.localdomain('.'))
    assert.is_nil(is.localdomain('.local'))
    assert.is_nil(is.localdomain('local'))
    assert.is_nil(is.localdomain({}))
    assert.is_nil(is.localdomain({'type'}))
    assert.is_nil(is.localdomain(0))
    assert.is_nil(is.localdomain(''))
    assert.is_nil(is.localdomain(false))
    assert.is_nil(is.localdomain(true))
  end)
  it("nil", function()
    assert.is_nil(is.localdomain(nil))
    assert.is_nil(is.localdomain())
  end)
end)