describe("is.public_email_provider", function()
	local t, is, domain
	setup(function()
    t = require "t"
    is = t.is
    domain = t.net.domain
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(domain))
    assert.truthy(is.callable(is.public_email_provider))
  end)
  it("positive", function()
    assert.is_nil(is.public_email_provider('hotmail.com'))
    assert.is_nil(is.public_email_provider(domain('hotmail.com')))
    assert.is_nil(is.public_email_provider('zzz.com'))
    assert.is_nil(is.public_email_provider(domain('zzz.com')))
  end)
  it("negative", function()
    assert.is_nil(is.public_email_provider('my.local'))
    assert.is_nil(is.public_email_provider(domain('my.local')))
    assert.is_nil(is.public_email_provider('8.8.8.8'))
    assert.is_nil(is.public_email_provider('com'))
    assert.is_nil(is.public_email_provider('.com'))
    assert.is_nil(is.public_email_provider('com.ru'))
    assert.is_nil(is.public_email_provider('.com.ru'))
    assert.is_nil(is.public_email_provider('.'))
    assert.is_nil(is.public_email_provider('.local'))
    assert.is_nil(is.public_email_provider('local'))
    assert.is_nil(is.public_email_provider({}))
    assert.is_nil(is.public_email_provider({'type'}))
    assert.is_nil(is.public_email_provider(0))
    assert.is_nil(is.public_email_provider(''))
    assert.is_nil(is.public_email_provider(false))
    assert.is_nil(is.public_email_provider(true))
  end)
  it("nil", function()
    assert.is_nil(is.public_email_provider(nil))
    assert.is_nil(is.public_email_provider())
  end)
end)